export const PROJECTS_REQUEST = "PROJECTS_REQUEST";
export const PROJECTS_SUCCESS = "PROJECTS_SUCCESS";
export const PROJECTS_FAILURE = "PROJECTS_FAILURE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const CREATE_SUCCESS = "CREATE_SUCCESS";
export const CREATE_FAILED = "CREATE_FAILED";

export const PROJECT_CREATE_SUCCESS = "PROJECT_CREATE_SUCCESS";
export const DELETE_FILE_SUCCESS = "DELETE_FILE_SUCCESS";
export const PROJECT_CREATE_FAILED = "PROJECT_CREATE_FAILED";
export const CREATE_FILE_SUCCESS = "CREATE_FILE_SUCCESS";
export const UPDATE_FILE_SUCCESS = "UPDATE_FILE_SUCCESS";
export const GET_FILE_SUCCESS = "GET_FILE_SUCCESS";
export const FILE_OPERATION_FAILURE = "FILE_OPERATION_FAILURE";


